### ISSUE TITLE
Problem with LESS

### ISSUE THREAD

**Issue by gerardo-navarro** [ixti/jekyll-assets#97]
When building my project I always get:

Liquid Exception: Cannot call method 'split' of undefined (in /website/_assets/stylesheets/style.css.less) in _includes/_header.html.erb, included in _layouts/portfolio-layout.html
jekyll 2.3.0 | Error:  Cannot call method 'split' of undefined

Did you experienced this issue?

My Gemfile looks like this:
```
source 'https://rubygems.org'
gem 'jekyll'
gem 'jekyll-assets'
gem 'therubyracer'
gem 'less'
gem 'uglifier'
gem 'yui-compressor'
```

My _config.yml looks like this:
```
name: Gerardo Navarro Suarez
destination: website
markdown: redcarpet
pygments: true
exclude: ['Gemfile', 'Gemfile.lock']
gems: ['jekyll-assets']
assets:
  js_compressor:  yui
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images
```

Let me know if you need any other information or files?
